# Generated by Django 4.2.6 on 2023-10-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolie', '0002_remove_person_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='img',
        ),
        migrations.AddField(
            model_name='person',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
